// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2538.PowerUp2538.subsystems;

import org.usfirst.frc2538.PowerUp2538.RobotMap;
import org.usfirst.frc2538.PowerUp2538.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class BoxClappers extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid doubleSolenoid5 = RobotMap.boxClappersDoubleSolenoid5;
    private final WPI_TalonSRX talonSRX8 = RobotMap.boxClappersTalonSRX8;
    private final WPI_TalonSRX talonSRX10 = RobotMap.boxClappersTalonSRX10;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final double speedSRX8 = 0.3;
    private final double speedSRX10=0.3;
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public boolean stop(){
    	talonSRX10.set(0);
    	talonSRX8.set(0);
    	return true;
    	}
    public void spinClappers(){
    	talonSRX10.set(speedSRX10);
    	talonSRX8.set(-speedSRX8);
    	SmartDashboard.putString("spin  clappers", "yes");
    }
    public void spitOutClappers(){
    	talonSRX10.set(-speedSRX10);
    	talonSRX8.set(speedSRX8);
    	SmartDashboard.putString("spit  clappers", "yes");
    	}
    public void extendClappers(){
    	doubleSolenoid5.set(DoubleSolenoid.Value.kForward);
    }
    public void retractClappers(){
    	doubleSolenoid5.set(DoubleSolenoid.Value.kReverse);
    }
}

